server:
  port: 9000
spring:

  datasource:
    url: jdbc:h2:file:./database/patient_db
    driverClassName: org.h2.Driver
    userName: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enable: true
    password:

